networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    networks:
      - kafka-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  java-producer:
    build:
      context: .
    container_name: java-producer
    depends_on:
      kafka:
        condition: service_started
    networks:
      - kafka-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  python-brain:
    build:
      context: ./anomaly-detection-brain
    container_name: python-brain
    depends_on:
      kafka:
        condition: service_started 
    networks:
      - kafka-net
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  react-ui:
    build:
      context: ./react_ui
    container_name: react-ui
    depends_on:
      python-brain:
        condition: service_started
    ports:
      - "5173:80"
    networks:
      - kafka-net
