spring.application.name=network-anomaly-detection

spring.kafka.producer.bootstrap-servers=localhost:9092

# format the keys and values
# standard String formatting for the Key
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Spring's built-in Jackson serializer - Java Object into perfect JSON
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer